In [2]:
import pandas as pd

In [4]:
%pwd

'/Users/smcaleese/Documents/masters-thesis-code/CLOSS/notebooks'

In [5]:
same_texts_as_baselines = pd.read_csv("../../input/imdb-input.csv")

In [16]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

id2label = {0: "NEGATIVE", 1: "POSITIVE"}
label2id = {"NEGATIVE": 0, "POSITIVE": 1}

model = AutoModelForSequenceClassification.from_pretrained(
    "textattack/bert-base-uncased-imdb", num_labels=2, id2label=id2label, label2id=label2id
)

In [17]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [18]:
tokenizer = AutoTokenizer.from_pretrained("textattack/bert-base-uncased-imdb")

In [19]:
sentence = "I loved the movie."
ids_tensor = tokenizer.encode(sentence, return_tensors="pt")
ids_tensor

tensor([[ 101, 1045, 3866, 1996, 3185, 1012,  102]])

In [20]:
tokens = tokenizer.tokenize(sentence)
tokens

['i', 'loved', 'the', 'movie', '.']

In [21]:
id_list = tokenizer.encode(sentence)
tokens = tokenizer.convert_ids_to_tokens(id_list)
tokens

['[CLS]', 'i', 'loved', 'the', 'movie', '.', '[SEP]']

In [22]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[101, 1045, 3866, 1996, 3185, 1012, 102]

In [23]:
sentence = tokenizer.decode(ids[1:-1])
sentence

'i loved the movie.'

In [24]:
sentence2 = tokenizer.convert_tokens_to_string(tokens)[6:-6]
sentence2

'i loved the movie.'

In [25]:
ids_tensor

tensor([[ 101, 1045, 3866, 1996, 3185, 1012,  102]])

In [26]:
import torch

with torch.no_grad():
    logits = model(ids_tensor).logits

logits

tensor([[-2.3390,  3.0285]])

In [27]:
predicted_class_id = logits.argmax().item() # 0
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [28]:
model.config.id2label[predicted_class_id]

'POSITIVE'