In [1]:
import pandas as pd

In [2]:
same_texts_as_baselines = pd.read_csv("roberta-base-imdb-short-10-log.csv")

In [47]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

id2label = {0: "NEGATIVE", 1: "POSITIVE"}
label2id = {"NEGATIVE": 0, "POSITIVE": 1}

model = AutoModelForSequenceClassification.from_pretrained(
    "textattack/bert-base-uncased-imdb", num_labels=2, id2label=id2label, label2id=label2id
)

In [48]:
tokenizer = AutoTokenizer.from_pretrained("textattack/bert-base-uncased-imdb")

In [60]:
sentence = "I loved the movie. It was fantastic."
# sentence = "I hated the movie. It was terrible."
ids_tensor = tokenizer.encode(sentence, return_tensors="pt")
ids_tensor

tensor([[  101,  1045,  3866,  1996,  3185,  1012,  2009,  2001, 10392,  1012,
           102]])

In [61]:
import torch

with torch.no_grad():
    logits = model(ids_tensor).logits

logits

tensor([[-1.9893,  2.8492]])

In [62]:
predicted_class_id = logits.argmax().item() # 0
# sentiment_model.config.id2label[predicted_class_id]
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [63]:
model.config.id2label[predicted_class_id]

'POSITIVE'

In [2]:
import torch

t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
t.view(-1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])