In [3]:
import pandas as pd

In [4]:
same_texts_as_baselines = pd.read_csv("../../input/imdb_input_sentences.csv")

In [5]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

id2label = {0: "NEGATIVE", 1: "POSITIVE"}
label2id = {"NEGATIVE": 0, "POSITIVE": 1}

model = AutoModelForSequenceClassification.from_pretrained(
    "textattack/bert-base-uncased-imdb", num_labels=2, id2label=id2label, label2id=label2id
)

/Users/smcaleese/Documents/masters-thesis-code/.env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [7]:
tokenizer = AutoTokenizer.from_pretrained("textattack/bert-base-uncased-imdb")

In [75]:
# sentence = "This movie was sadly under-promoted but proved to be truly exceptional. Entering the theatre I knew nothing about the film except that a friend wanted to see it. I was caught off guard with the high quality of the film. I couldn't image Ashton Kutcher in a serious role, but his performance truly exemplified his character. This movie is exceptional and deserves our monetary support, unlike so many other movies. It does not come lightly for me to recommend any movie, but in this case I highly recommend that everyone see it. This films is Truly Exceptional!"
# sentence = "On a dark, gloomy New Year's Eve night, an ill nurse, her life slowly ebbing away, demands that David Holm be presented to her at once. We don't yet know who David Holm is, or why this nurse wishes to see him, but her only dying wish is to speak with him just one more time. On the other side of the town, nestled comfortably amongst the gravestones of the local cemetery, Holm (Victor Sjöström, who also directed) and two of his drunken associates merrily await the coming of the New Year. ""Here we can tell just when to drink the New Year in,"" exclaims Holm, casting a finger towards the large clock tower that looms through the darkness. Little does he know, however, that he will not be alive to greet it. To pass the time, Holm cheerfully recites a ghost story. He'd once had a friend name George, ""a merry fellow"" who was ""smarter than the rest of us."" On one New Year's Eve several years ago, George has broken up a potentially disastrous brawl, fearing that the final man to draw his last breath before midnight would be condemned to drive the phantom chariot for the next year, doing Death's bidding and collecting the souls of the deceased. ""And, gentlemen, George died last New Year's Eve!"" concludes Holm happily, not bothering to contain his mocking skepticism of the man's beliefs. As fate has it, of course, an unexpected violent encounter results in Holm's death, just on the stroke of midnight. As the man's transparent spirit rises gingerly from his earthly body, he witnesses, to his horror, the distant approach of a phantom carriage. The driver, a frail cloaked figure - a sickle clasped tightly in his hand - steps down from the carriage and approaches. We are astonished to discover that the driver is none other than a decrepit George, preparing to pass on his ghastly duty to this year's successor. Considering the era in which 'Körkarlen' is made, the special effects in this film are absolutely superb. Cinematographer Julius Jaenzon used double-exposure photography to create the eerie, ghostly silhouette of the carriage and its damned driver. Even today, the end result is highly effective. A particularly impressive scene involves the phantom chariot travelling to the ocean floor to retrieve the soul of a drowned man. Another scene, eerily reminiscent of Jack Torrance (Jack Nicholson) in Stanley Kubrick's 'The Shining,' involves Holm breaking down the kitchen door with an axe in order to reach his fleeing wife and children. Genuinely ominous and unsettling in its execution, Victor Sjöström's 'Körkarlen' is a fine work of cinema, successfully portraying Holm's steady alcoholic decline, his inevitable day of judgment, and a final hopeful possibility of redemption."
# sentence = "Just saw this movie on opening night. I read some other user comments which convinced me to go see it... I must say, I was not impressed. I'm so unimpressed that I feel the need to write this comment to spare some of you people some money. First of all ""The Messengers"" is very predictable, and just not much of a thriller. It might be scary for someone under 13, but it really did nothing for me. The climax was laughable and most of the audience left before the movie's resolution. Furthermore the acting seemed a little superficial. Some of the emotional arguments between the family were less convincing than the sub-par suspense scenes. If you've seen previews for this movie, then you've seen most of the best parts and have a strong understanding of the plot. This movie is not worth seeing in the theaters."
sentence = "What a mess--and I'm not referring to the ""destruction"" in the title. I could go on about the hackneyed plot, the lousy effects, the (actually notable) cast grimacing as they deliver the worst lines of their careers, etc. I'll just say there weren't any palm trees in Chicago the last time I checked, and leave it at that. Hmmm...need ten lines to get this posted on IMDb.. OK, well, I think a DVD release with outtakes could be interesting. Maybe Dennehy will reveal what favor got called in for him to appear in this thing. Maybe Dianne Weist will show us the bag of money it must have taken to get her involved. Maybe CBS execs will apologize..."
# sentence = "I hated the movie. It was terrible."
ids_tensor = tokenizer.encode(sentence, return_tensors="pt")
ids_tensor

tensor([[  101,  2054,  1037,  6752,  1011,  1011,  1998,  1045,  1005,  1049,
          2025,  7727,  2000,  1996,  6215,  1999,  1996,  2516,  1012,  1045,
          2071,  2175,  2006,  2055,  1996, 28425,  2098,  5436,  1010,  1996,
         10223,  6508,  3896,  1010,  1996,  1006,  2941,  3862,  1007,  3459,
         11844, 26217,  2004,  2027,  8116,  1996,  5409,  3210,  1997,  2037,
         10922,  1010,  4385,  1012,  1045,  1005,  2222,  2074,  2360,  2045,
          4694,  1005,  1056,  2151,  5340,  3628,  1999,  3190,  1996,  2197,
          2051,  1045,  7039,  1010,  1998,  2681,  2009,  2012,  2008,  1012,
         17012,  2213,  1012,  1012,  1012,  2342,  2702,  3210,  2000,  2131,
          2023,  6866,  2006, 10047, 18939,  1012,  1012,  7929,  1010,  2092,
          1010,  1045,  2228,  1037,  4966,  2713,  2007, 24955,  9681,  2071,
          2022,  5875,  1012,  2672,  7939,  2638, 10536,  2097,  7487,  2054,
          5684,  2288,  2170,  1999,  2005,  2032,  

In [76]:
tokens = tokenizer.tokenize(sentence)
tokens

['what',
 'a',
 'mess',
 '-',
 '-',
 'and',
 'i',
 "'",
 'm',
 'not',
 'referring',
 'to',
 'the',
 'destruction',
 'in',
 'the',
 'title',
 '.',
 'i',
 'could',
 'go',
 'on',
 'about',
 'the',
 'hackney',
 '##ed',
 'plot',
 ',',
 'the',
 'lou',
 '##sy',
 'effects',
 ',',
 'the',
 '(',
 'actually',
 'notable',
 ')',
 'cast',
 'grim',
 '##acing',
 'as',
 'they',
 'deliver',
 'the',
 'worst',
 'lines',
 'of',
 'their',
 'careers',
 ',',
 'etc',
 '.',
 'i',
 "'",
 'll',
 'just',
 'say',
 'there',
 'weren',
 "'",
 't',
 'any',
 'palm',
 'trees',
 'in',
 'chicago',
 'the',
 'last',
 'time',
 'i',
 'checked',
 ',',
 'and',
 'leave',
 'it',
 'at',
 'that',
 '.',
 'hmm',
 '##m',
 '.',
 '.',
 '.',
 'need',
 'ten',
 'lines',
 'to',
 'get',
 'this',
 'posted',
 'on',
 'im',
 '##db',
 '.',
 '.',
 'ok',
 ',',
 'well',
 ',',
 'i',
 'think',
 'a',
 'dvd',
 'release',
 'with',
 'outta',
 '##kes',
 'could',
 'be',
 'interesting',
 '.',
 'maybe',
 'den',
 '##ne',
 '##hy',
 'will',
 'reveal',
 'what',
 '

In [77]:
id_list = tokenizer.encode(sentence)
tokens = tokenizer.convert_ids_to_tokens(id_list)
tokens

['[CLS]',
 'what',
 'a',
 'mess',
 '-',
 '-',
 'and',
 'i',
 "'",
 'm',
 'not',
 'referring',
 'to',
 'the',
 'destruction',
 'in',
 'the',
 'title',
 '.',
 'i',
 'could',
 'go',
 'on',
 'about',
 'the',
 'hackney',
 '##ed',
 'plot',
 ',',
 'the',
 'lou',
 '##sy',
 'effects',
 ',',
 'the',
 '(',
 'actually',
 'notable',
 ')',
 'cast',
 'grim',
 '##acing',
 'as',
 'they',
 'deliver',
 'the',
 'worst',
 'lines',
 'of',
 'their',
 'careers',
 ',',
 'etc',
 '.',
 'i',
 "'",
 'll',
 'just',
 'say',
 'there',
 'weren',
 "'",
 't',
 'any',
 'palm',
 'trees',
 'in',
 'chicago',
 'the',
 'last',
 'time',
 'i',
 'checked',
 ',',
 'and',
 'leave',
 'it',
 'at',
 'that',
 '.',
 'hmm',
 '##m',
 '.',
 '.',
 '.',
 'need',
 'ten',
 'lines',
 'to',
 'get',
 'this',
 'posted',
 'on',
 'im',
 '##db',
 '.',
 '.',
 'ok',
 ',',
 'well',
 ',',
 'i',
 'think',
 'a',
 'dvd',
 'release',
 'with',
 'outta',
 '##kes',
 'could',
 'be',
 'interesting',
 '.',
 'maybe',
 'den',
 '##ne',
 '##hy',
 'will',
 'reveal',
 

In [19]:
# convert that list of tokens into a normal sentence again:

ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[101, 1045, 3866, 1996, 3185, 1012, 2009, 2001, 10392, 1012, 102]

In [22]:
# convert the ids to a string:
sentence = tokenizer.decode(ids[1:-1])
sentence

'i loved the movie. it was fantastic.'

In [28]:
# or you can convert the tokens to a string directly:

sentence2 = tokenizer.convert_tokens_to_string(tokens)[6:-6]
sentence2

'i loved the movie. it was fantastic.'

In [9]:
import torch

with torch.no_grad():
    logits = model(ids_tensor).logits

logits

tensor([[-1.9893,  2.8492]])

In [62]:
predicted_class_id = logits.argmax().item() # 0
# sentiment_model.config.id2label[predicted_class_id]
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [63]:
model.config.id2label[predicted_class_id]

'POSITIVE'

In [2]:
import torch

t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
t.view(-1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Join tokens again into a sentence.

In [78]:
 tokens = ['[CLS]',
 'what',
 'a',
 'mess',
 '-',
 '-',
 'and',
 'i',
 "'",
 'm',
 'not',
 'referring',
 'to',
 'the',
 'destruction',
 'in',
 'the',
 'title',
 '.',
 'i',
 'could',
 'go',
 'on',
 'about',
 'the',
 'hackney',
 '##ed',
 'plot',
 ',',
 'the',
 'lou',
 '##sy',
 'effects',
 ',',
 'the',
 '(',
 'actually',
 'notable',
 ')',
 'cast',
 'grim',
 '##acing',
 'as',
 'they',
 'deliver',
 'the',
 'worst',
 'lines',
 'of',
 'their',
 'careers',
 ',',
 'etc',
 '.',
 'i',
 "'",
 'll',
 'just',
 'say',
 'there',
 'weren',
 "'",
 't',
 'any',
 'palm',
 'trees',
 'in',
 'chicago',
 'the',
 'last',
 'time',
 'i',
 'checked',
 ',',
 'and',
 'leave',
 'it',
 'at',
 'that',
 '.',
 'hmm',
 '##m',
 '.',
 '.',
 '.',
 'need',
 'ten',
 'lines',
 'to',
 'get',
 'this',
 'posted',
 'on',
 'im',
 '##db',
 '.',
 '.',
 'ok',
 ',',
 'well',
 ',',
 'i',
 'think',
 'a',
 'dvd',
 'release',
 'with',
 'outta',
 '##kes',
 'could',
 'be',
 'interesting',
 '.',
 'maybe',
 'den',
 '##ne',
 '##hy',
 'will',
 'reveal',
 'what',
 'favor',
 'got',
 'called',
 'in',
 'for',
 'him',
 'to',
 'appear',
 'in',
 'this',
 'thing',
 '.',
 'maybe',
 'dia',
 '##nne',
 'wei',
 '##st',
 'will',
 'show',
 'us',
 'the',
 'bag',
 'of',
 'money',
 'it',
 'must',
 'have',
 'taken',
 'to',
 'get',
 'her',
 'involved',
 '.',
 'maybe',
 'cbs',
 'ex',
 '##ec',
 '##s',
 'will',
 'apologize',
 '.',
 '.',
 '.',
 '[SEP]']


In [79]:
new_text_lower = tokenizer.convert_tokens_to_string(tokens)
new_text_lower

"[CLS] what a mess - - and i ' m not referring to the destruction in the title. i could go on about the hackneyed plot, the lousy effects, the ( actually notable ) cast grimacing as they deliver the worst lines of their careers, etc. i ' ll just say there weren ' t any palm trees in chicago the last time i checked, and leave it at that. hmmm... need ten lines to get this posted on imdb.. ok, well, i think a dvd release with outtakes could be interesting. maybe dennehy will reveal what favor got called in for him to appear in this thing. maybe dianne weist will show us the bag of money it must have taken to get her involved. maybe cbs execs will apologize... [SEP]"

In [80]:
def format_output_text(text):
    """After the tokens have been converted to a string, this function formats the text to be more readable."""

    # Removing the special tokens [CLS] and [SEP]
    sentence = text[6:-6]
    
    # Handling spaces around punctuation
    sentence = sentence.replace(" ' ", "'").replace(" - ", "-")

    # capitalize each sentence and each "i"
    sentence = ". ".join([s.capitalize() for s in sentence.split(". ")])
    sentence = sentence.replace(" i ", " I ")

    return sentence

sentence = list_to_sentence(new_text_lower)
print(sentence)

What a mess-- and i'm not referring to the destruction in the title. I could go on about the hackneyed plot, the lousy effects, the ( actually notable ) cast grimacing as they deliver the worst lines of their careers, etc. I'll just say there weren't any palm trees in chicago the last time I checked, and leave it at that. Hmmm... Need ten lines to get this posted on imdb.. Ok, well, I think a dvd release with outtakes could be interesting. Maybe dennehy will reveal what favor got called in for him to appear in this thing. Maybe dianne weist will show us the bag of money it must have taken to get her involved. Maybe cbs execs will apologize...
